const fs=require('fs'),vm=require('vm'),assert=require('assert'),path=require('path');
process.chdir(path.resolve(__dirname,'..'));global.THREE=require('../vendor/three.min.js');require('../vendor/GLTFLoader.js');
const bytes=fs.readFileSync('assets/knox.glb');new THREE.GLTFLoader().parse(bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength),'',gltf=>{
 const root=gltf.scene,tilt=new THREE.Group();tilt.add(root);root.updateMatrixWorld(true);let KB={},mesh;root.traverse(n=>{if(n.isSkinnedMesh)mesh=n;if(n.isBone){let q=new THREE.Quaternion(),p=new THREE.Quaternion();n.getWorldQuaternion(q);n.parent.getWorldQuaternion(p);KB[n.name]={bone:n,rest:q,pInv:p.invert(),local:n.quaternion.clone()}}});
 const gun=new THREE.Group();tilt.add(gun);let k={tilt,gun,mw:0,aw:0,sitw:0,kick:0,walk:0,speed:1,flash:{material:{}},beam:{material:{}}};const source=fs.readFileSync('game.js','utf8');
 let context={THREE,KB,knox:k,T:0,PI:Math.PI,_E:new THREE.Euler(0,0,0,'YXZ'),_Q:new THREE.Quaternion(),_V:new THREE.Vector3(),clamp:(v,a,b)=>Math.min(b,Math.max(a,v)),lerp:(a,b,t)=>a+(b-a)*t};vm.createContext(context);
 vm.runInContext(source.slice(source.indexOf('function setB('),source.indexOf('/* toy dream-blaster */')),context);vm.runInContext(source.slice(source.indexOf('var armQ='),source.indexOf('function fallbackKnox')),context);
 function lowerVertices(){tilt.updateMatrixWorld(true);mesh.skeleton.update();const p=mesh.geometry.attributes.position,out=[];for(let i=0;i<p.count;i++)if(p.getY(i)<.75)out.push(mesh.boneTransform(i,new THREE.Vector3(p.getX(i),p.getY(i),p.getZ(i))).applyMatrix4(mesh.matrixWorld));return out;}
 context.animKnox(1,{move:0,aim:false,rest:true});const idle=lowerVertices();for(let i=0;i<30;i++)context.animKnox(1/60,{move:0,aim:true,gunOk:true});const aim=lowerVertices();let shift=0;for(let i=0;i<idle.length;i++)shift=Math.max(shift,idle[i].distanceTo(aim[i]));assert(shift<.025,'Shooting pulls lower-body vertices: '+shift);
 let rest=KB.LeftLeg.bone.getWorldPosition(new THREE.Vector3());for(let phase=0;phase<16;phase++){k.walk=phase/16*Math.PI*2;context.animKnox(.1,{move:1,aim:true,gunOk:true});tilt.updateMatrixWorld(true);assert(Object.values(KB).every(b=>b.bone.matrixWorld.elements.every(Number.isFinite)));}
 let moved=rest.distanceTo(KB.LeftLeg.bone.getWorldPosition(new THREE.Vector3()));assert(moved>.01,'Gait does not move knee');console.log(JSON.stringify({passed:true,checks:['Lower body stays stable when arms aim','Gait moves knee','All joint matrices remain finite across 16 walk-and-fire poses'],maxLowerBodyShiftDuringAim:shift,kneeMovement:moved},null,2));
},e=>{console.error(e);process.exit(1)});
